# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: uala-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uala
    ports:
      - "5432:5432"
    volumes:
      - uala_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  uala_pgdata:
